// 300 häufigste schwedische Wörter – optimiert zum schnellen Lernen
// Kategorien: noun, verb, prep, other
// Nomen: gender (en/ett), singular, plural
// Verben: infinitive, present (Präsens)

const VOCAB = [
  // === VERBEN (ca. 70) ===
  { id:1, se:"vara", de:"sein", cat:"verb", inf:"vara", pres:"är" },
  { id:2, se:"ha", de:"haben", cat:"verb", inf:"ha", pres:"har" },
  { id:3, se:"kunna", de:"können", cat:"verb", inf:"kunna", pres:"kan" },
  { id:4, se:"ska", de:"sollen / werden (Futur)", cat:"verb", inf:"ska", pres:"ska" },
  { id:5, se:"få", de:"bekommen / dürfen", cat:"verb", inf:"få", pres:"får" },
  { id:6, se:"bli", de:"werden", cat:"verb", inf:"bli", pres:"blir" },
  { id:7, se:"komma", de:"kommen", cat:"verb", inf:"komma", pres:"kommer" },
  { id:8, se:"göra", de:"machen / tun", cat:"verb", inf:"göra", pres:"gör" },
  { id:9, se:"ta", de:"nehmen", cat:"verb", inf:"ta", pres:"tar" },
  { id:10, se:"gå", de:"gehen", cat:"verb", inf:"gå", pres:"går" },
  { id:11, se:"säga", de:"sagen", cat:"verb", inf:"säga", pres:"säger" },
  { id:12, se:"se", de:"sehen", cat:"verb", inf:"se", pres:"ser" },
  { id:13, se:"vilja", de:"wollen", cat:"verb", inf:"vilja", pres:"vill" },
  { id:14, se:"ge", de:"geben", cat:"verb", inf:"ge", pres:"ger" },
  { id:15, se:"måste", de:"müssen", cat:"verb", inf:"måste", pres:"måste" },
  { id:16, se:"behöva", de:"brauchen / benötigen", cat:"verb", inf:"behöva", pres:"behöver" },
  { id:17, se:"börja", de:"beginnen / anfangen", cat:"verb", inf:"börja", pres:"börjar" },
  { id:18, se:"visa", de:"zeigen", cat:"verb", inf:"visa", pres:"visar" },
  { id:19, se:"hålla", de:"halten", cat:"verb", inf:"hålla", pres:"håller" },
  { id:20, se:"skriva", de:"schreiben", cat:"verb", inf:"skriva", pres:"skriver" },
  { id:21, se:"använda", de:"benutzen / verwenden", cat:"verb", inf:"använda", pres:"använder" },
  { id:22, se:"stå", de:"stehen", cat:"verb", inf:"stå", pres:"står" },
  { id:23, se:"ligga", de:"liegen", cat:"verb", inf:"ligga", pres:"ligger" },
  { id:24, se:"veta", de:"wissen", cat:"verb", inf:"veta", pres:"vet" },
  { id:25, se:"spela", de:"spielen", cat:"verb", inf:"spela", pres:"spelar" },
  { id:26, se:"tro", de:"glauben / denken", cat:"verb", inf:"tro", pres:"tror" },
  { id:27, se:"öka", de:"erhöhen / zunehmen", cat:"verb", inf:"öka", pres:"ökar" },
  { id:28, se:"hitta", de:"finden", cat:"verb", inf:"hitta", pres:"hittar" },
  { id:29, se:"tänka", de:"denken", cat:"verb", inf:"tänka", pres:"tänker" },
  { id:30, se:"fortsätta", de:"fortsetzen / weitermachen", cat:"verb", inf:"fortsätta", pres:"fortsätter" },
  { id:31, se:"lägga", de:"legen / legen", cat:"verb", inf:"lägga", pres:"lägger" },
  { id:32, se:"sitta", de:"sitzen", cat:"verb", inf:"sitta", pres:"sitter" },
  { id:33, se:"tycka", de:"finden / meinen", cat:"verb", inf:"tycka", pres:"tycker" },
  { id:34, se:"finna", de:"finden / es gibt", cat:"verb", inf:"finnas", pres:"finns" },
  { id:35, se:"läsa", de:"lesen", cat:"verb", inf:"läsa", pres:"läser" },
  { id:36, se:"tala", de:"sprechen", cat:"verb", inf:"tala", pres:"talar" },
  { id:37, se:"äta", de:"essen", cat:"verb", inf:"äta", pres:"äter" },
  { id:38, se:"dricka", de:"trinken", cat:"verb", inf:"dricka", pres:"dricker" },
  { id:39, se:"bo", de:"wohnen", cat:"verb", inf:"bo", pres:"bor" },
  { id:40, se:"arbeta", de:"arbeiten", cat:"verb", inf:"arbeta", pres:"arbetar" },
  { id:41, se:"köpa", de:"kaufen", cat:"verb", inf:"köpa", pres:"köper" },
  { id:42, se:"sälja", de:"verkaufen", cat:"verb", inf:"sälja", pres:"säljer" },
  { id:43, se:"öppna", de:"öffnen", cat:"verb", inf:"öppna", pres:"öppnar" },
  { id:44, se:"stänga", de:"schließen", cat:"verb", inf:"stänga", pres:"stänger" },
  { id:45, se:"hjälpa", de:"helfen", cat:"verb", inf:"hjälpa", pres:"hjälper" },
  { id:46, se:"fråga", de:"fragen", cat:"verb", inf:"fråga", pres:"frågar" },
  { id:47, se:"svarar", de:"antworten", cat:"verb", inf:"svara", pres:"svarar" },
  { id:48, se:"förstå", de:"verstehen", cat:"verb", inf:"förstå", pres:"förstår" },
  { id:49, se:"lära", de:"lernen / lehren", cat:"verb", inf:"lära", pres:"lär" },
  { id:50, se:"sova", de:"schlafen", cat:"verb", inf:"sova", pres:"sover" },
  { id:51, se:"leva", de:"leben", cat:"verb", inf:"leva", pres:"lever" },
  { id:52, se:"känna", de:"fühlen / kennen", cat:"verb", inf:"känna", pres:"känner" },
  { id:53, se:"höra", de:"hören", cat:"verb", inf:"höra", pres:"hör" },
  { id:54, se:"titta", de:"schauen / gucken", cat:"verb", inf:"titta", pres:"tittar" },
  { id:55, se:"vänta", de:"warten", cat:"verb", inf:"vänta", pres:"väntar" },
  { id:56, se:"ringa", de:"anrufen / klingeln", cat:"verb", inf:"ringa", pres:"ringer" },
  { id:57, se:"betala", de:"bezahlen", cat:"verb", inf:"betala", pres:"betalar" },
  { id:58, se:"resa", de:"reisen", cat:"verb", inf:"resa", pres:"reser" },
  { id:59, se:"träffa", de:"treffen", cat:"verb", inf:"träffa", pres:"träffar" },
  { id:60, se:"älska", de:"lieben", cat:"verb", inf:"älska", pres:"älskar" },
  { id:61, se:"gilla", de:"mögen", cat:"verb", inf:"gilla", pres:"gillar" },
  { id:62, se:"hoppas", de:"hoffen", cat:"verb", inf:"hoppas", pres:"hoppas" },
  { id:63, se:"besöka", de:"besuchen", cat:"verb", inf:"besöka", pres:"besöker" },
  { id:64, se:"jobba", de:"arbeiten (umgangssprachlich)", cat:"verb", inf:"jobba", pres:"jobbar" },
  { id:65, se:"studera", de:"studieren", cat:"verb", inf:"studera", pres:"studerar" },
  { id:66, se:"leva", de:"leben", cat:"verb", inf:"leva", pres:"lever" },
  { id:67, se:"dö", de:"sterben", cat:"verb", inf:"dö", pres:"dör" },
  { id:68, se:"springa", de:"rennen / laufen", cat:"verb", inf:"springa", pres:"springer" },
  { id:69, se:"cykla", de:"Rad fahren", cat:"verb", inf:"cykla", pres:"cyklar" },
  { id:70, se:"köra", de:"fahren (Auto)", cat:"verb", inf:"köra", pres:"kör" },

  // === NOMEN (ca. 110) ===
  { id:101, se:"år", de:"Jahr", cat:"noun", gender:"ett", singular:"år", plural:"år" },
  { id:102, se:"dag", de:"Tag", cat:"noun", gender:"en", singular:"dag", plural:"dagar" },
  { id:103, se:"tid", de:"Zeit", cat:"noun", gender:"en", singular:"tid", plural:"tider" },
  { id:104, se:"person", de:"Person", cat:"noun", gender:"en", singular:"person", plural:"personer" },
  { id:105, se:"barn", de:"Kind", cat:"noun", gender:"ett", singular:"barn", plural:"barn" },
  { id:106, se:"land", de:"Land / Land", cat:"noun", gender:"ett", singular:"land", plural:"länder" },
  { id:107, se:"del", de:"Teil", cat:"noun", gender:"en", singular:"del", plural:"delar" },
  { id:108, se:"gång", de:"Mal / Gang", cat:"noun", gender:"en", singular:"gång", plural:"gånger" },
  { id:109, se:"vecka", de:"Woche", cat:"noun", gender:"en", singular:"vecka", plural:"veckor" },
  { id:110, se:"plats", de:"Platz / Ort", cat:"noun", gender:"en", singular:"plats", plural:"platser" },
  { id:111, se:"fråga", de:"Frage", cat:"noun", gender:"en", singular:"fråga", plural:"frågor" },
  { id:112, se:"sätt", de:"Art / Weise", cat:"noun", gender:"ett", singular:"sätt", plural:"sätt" },
  { id:113, se:"människa", de:"Mensch", cat:"noun", gender:"en", singular:"människa", plural:"människor" },
  { id:114, se:"bild", de:"Bild", cat:"noun", gender:"en", singular:"bild", plural:"bilder" },
  { id:115, se:"krona", de:"Krone (Währung)", cat:"noun", gender:"en", singular:"krona", plural:"kronor" },
  { id:116, se:"företag", de:"Unternehmen / Firma", cat:"noun", gender:"ett", singular:"företag", plural:"företag" },
  { id:117, se:"väg", de:"Weg / Straße", cat:"noun", gender:"en", singular:"väg", plural:"vägar" },
  { id:118, se:"liv", de:"Leben", cat:"noun", gender:"ett", singular:"liv", plural:"liv" },
  { id:119, se:"värld", de:"Welt", cat:"noun", gender:"en", singular:"värld", plural:"världar" },
  { id:120, se:"kommun", de:"Gemeinde / Kommune", cat:"noun", gender:"en", singular:"kommun", plural:"kommuner" },
  { id:121, se:"procent", de:"Prozent", cat:"noun", gender:"en", singular:"procent", plural:"procent" },
  { id:122, se:"arbete", de:"Arbeit", cat:"noun", gender:"ett", singular:"arbete", plural:"arbeten" },
  { id:123, se:"stad", de:"Stadt", cat:"noun", gender:"en", singular:"stad", plural:"städer" },
  { id:124, se:"hus", de:"Haus", cat:"noun", gender:"ett", singular:"hus", plural:"hus" },
  { id:125, se:"man", de:"Mann", cat:"noun", gender:"en", singular:"man", plural:"män" },
  { id:126, se:"kvinna", de:"Frau", cat:"noun", gender:"en", singular:"kvinna", plural:"kvinnor" },
  { id:127, se:"vän", de:"Freund / Freundin", cat:"noun", gender:"en", singular:"vän", plural:"vänner" },
  { id:128, se:"familj", de:"Familie", cat:"noun", gender:"en", singular:"familj", plural:"familjer" },
  { id:129, se:"bok", de:"Buch", cat:"noun", gender:"en", singular:"bok", plural:"böcker" },
  { id:130, se:"skola", de:"Schule", cat:"noun", gender:"en", singular:"skola", plural:"skolor" },
  { id:131, se:"jobb", de:"Job / Arbeit", cat:"noun", gender:"ett", singular:"jobb", plural:"jobb" },
  { id:132, se:"bil", de:"Auto", cat:"noun", gender:"en", singular:"bil", plural:"bilar" },
  { id:133, se:"vatten", de:"Wasser", cat:"noun", gender:"ett", singular:"vatten", plural:"vatten" },
  { id:134, se:"mat", de:"Essen / Lebensmittel", cat:"noun", gender:"en", singular:"mat", plural:"mater" },
  { id:135, se:"pengar", de:"Geld", cat:"noun", gender:"en", singular:"pengar", plural:"pengar" },
  { id:136, se:"hand", de:"Hand", cat:"noun", gender:"en", singular:"hand", plural:"händer" },
  { id:137, se:"öga", de:"Auge", cat:"noun", gender:"ett", singular:"öga", plural:"ögon" },
  { id:138, se:"huvud", de:"Kopf / Haupt", cat:"noun", gender:"ett", singular:"huvud", plural:"huvuden" },
  { id:139, se:"rum", de:"Zimmer / Raum", cat:"noun", gender:"ett", singular:"rum", plural:"rum" },
  { id:140, se:"bord", de:"Tisch", cat:"noun", gender:"ett", singular:"bord", plural:"bord" },
  { id:141, se:"stol", de:"Stuhl", cat:"noun", gender:"en", singular:"stol", plural:"stolar" },
  { id:142, se:"fönster", de:"Fenster", cat:"noun", gender:"ett", singular:"fönster", plural:"fönster" },
  { id:143, se:"dörr", de:"Tür", cat:"noun", gender:"en", singular:"dörr", plural:"dörrar" },
  { id:144, se:"telefon", de:"Telefon", cat:"noun", gender:"en", singular:"telefon", plural:"telefoner" },
  { id:145, se:"dator", de:"Computer", cat:"noun", gender:"en", singular:"dator", plural:"datorer" },
  { id:146, se:"ord", de:"Wort", cat:"noun", gender:"ett", singular:"ord", plural:"ord" },
  { id:147, se:"språk", de:"Sprache", cat:"noun", gender:"ett", singular:"språk", plural:"språk" },
  { id:148, se:"namn", de:"Name", cat:"noun", gender:"ett", singular:"namn", plural:"namn" },
  { id:149, se:"nummer", de:"Nummer", cat:"noun", gender:"ett", singular:"nummer", plural:"nummer" },
  { id:150, se:"sida", de:"Seite", cat:"noun", gender:"en", singular:"sida", plural:"sidor" },
  { id:151, se:"månad", de:"Monat", cat:"noun", gender:"en", singular:"månad", plural:"månader" },
  { id:152, se:"år", de:"Jahr", cat:"noun", gender:"ett", singular:"år", plural:"år" },
  { id:153, se:"timme", de:"Stunde", cat:"noun", gender:"en", singular:"timme", plural:"timmar" },
  { id:154, se:"minut", de:"Minute", cat:"noun", gender:"en", singular:"minut", plural:"minuter" },
  { id:155, se:"morgon", de:"Morgen", cat:"noun", gender:"en", singular:"morgon", plural:"morgnar" },
  { id:156, se:"kväll", de:"Abend", cat:"noun", gender:"en", singular:"kväll", plural:"kvällar" },
  { id:157, se:"natt", de:"Nacht", cat:"noun", gender:"en", singular:"natt", plural:"nätter" },
  { id:158, se:"sommar", de:"Sommer", cat:"noun", gender:"en", singular:"sommar", plural:"somrar" },
  { id:159, se:"vinter", de:"Winter", cat:"noun", gender:"en", singular:"vinter", plural:"vintrar" },
  { id:160, se:"höst", de:"Herbst", cat:"noun", gender:"en", singular:"höst", plural:"höstar" },
  { id:161, se:"vår", de:"Frühling", cat:"noun", gender:"en", singular:"vår", plural:"vårar" },
  { id:162, se:"sol", de:"Sonne", cat:"noun", gender:"en", singular:"sol", plural:"solar" },
  { id:163, se:"regn", de:"Regen", cat:"noun", gender:"ett", singular:"regn", plural:"regn" },
  { id:164, se:"snö", de:"Schnee", cat:"noun", gender:"en", singular:"snö", plural:"snöar" },
  { id:165, se:"väder", de:"Wetter", cat:"noun", gender:"ett", singular:"väder", plural:"väder" },
  { id:166, se:"kaffe", de:"Kaffee", cat:"noun", gender:"ett", singular:"kaffe", plural:"kaffe" },
  { id:167, se:"te", de:"Tee", cat:"noun", gender:"ett", singular:"te", plural:"te" },
  { id:168, se:"mjölk", de:"Milch", cat:"noun", gender:"en", singular:"mjölk", plural:"mjölk" },
  { id:169, se:"bröd", de:"Brot", cat:"noun", gender:"ett", singular:"bröd", plural:"bröd" },
  { id:170, se:"ost", de:"Käse", cat:"noun", gender:"en", singular:"ost", plural:"ostar" },
  { id:171, se:"äpple", de:"Apfel", cat:"noun", gender:"ett", singular:"äpple", plural:"äpplen" },
  { id:172, se:"fisk", de:"Fisch", cat:"noun", gender:"en", singular:"fisk", plural:"fiskar" },
  { id:173, se:"kött", de:"Fleisch", cat:"noun", gender:"ett", singular:"kött", plural:"kött" },
  { id:174, se:"restaurang", de:"Restaurant", cat:"noun", gender:"en", singular:"restaurang", plural:"restauranger" },
  { id:175, se:"butik", de:"Geschäft / Laden", cat:"noun", gender:"en", singular:"butik", plural:"butiker" },
  { id:176, se:"affär", de:"Geschäft", cat:"noun", gender:"en", singular:"affär", plural:"affärer" },
  { id:177, se:"pris", de:"Preis", cat:"noun", gender:"ett", singular:"pris", plural:"priser" },
  { id:178, se:"konto", de:"Konto", cat:"noun", gender:"ett", singular:"konto", plural:"konton" },
  { id:179, se:"bank", de:"Bank", cat:"noun", gender:"en", singular:"bank", plural:"banker" },
  { id:180, se:"tåg", de:"Zug", cat:"noun", gender:"ett", singular:"tåg", plural:"tåg" },
  { id:181, se:"buss", de:"Bus", cat:"noun", gender:"en", singular:"buss", plural:"bussar" },
  { id:182, se:"flyg", de:"Flug", cat:"noun", gender:"ett", singular:"flyg", plural:"flyg" },
  { id:183, se:"station", de:"Bahnhof / Station", cat:"noun", gender:"en", singular:"station", plural:"stationer" },
  { id:184, se:"hotell", de:"Hotel", cat:"noun", gender:"ett", singular:"hotell", plural:"hotell" },
  { id:185, se:"rum", de:"Zimmer", cat:"noun", gender:"ett", singular:"rum", plural:"rum" },
  { id:186, se:"nyckel", de:"Schlüssel", cat:"noun", gender:"en", singular:"nyckel", plural:"nycklar" },
  { id:187, se:"karta", de:"Karte / Landkarte", cat:"noun", gender:"en", singular:"karta", plural:"kartor" },
  { id:188, se:"adress", de:"Adresse", cat:"noun", gender:"en", singular:"adress", plural:"adresser" },
  { id:189, se:"brev", de:"Brief", cat:"noun", gender:"ett", singular:"brev", plural:"brev" },
  { id:190, se:"e-post", de:"E-Mail", cat:"noun", gender:"en", singular:"e-post", plural:"e-poster" },
  { id:191, se:"problem", de:"Problem", cat:"noun", gender:"ett", singular:"problem", plural:"problem" },
  { id:192, se:"möjlighet", de:"Möglichkeit", cat:"noun", gender:"en", singular:"möjlighet", plural:"möjligheter" },
  { id:193, se:"information", de:"Information", cat:"noun", gender:"en", singular:"information", plural:"informationer" },
  { id:194, se:"tjänst", de:"Dienst / Service", cat:"noun", gender:"en", singular:"tjänst", plural:"tjänster" },
  { id:195, se:"hälsa", de:"Gesundheit", cat:"noun", gender:"en", singular:"hälsa", plural:"hälsor" },
  { id:196, se:"sjukhus", de:"Krankenhaus", cat:"noun", gender:"ett", singular:"sjukhus", plural:"sjukhus" },
  { id:197, se:"läkare", de:"Arzt / Ärztin", cat:"noun", gender:"en", singular:"läkare", plural:"läkare" },
  { id:198, se:"apotek", de:"Apotheke", cat:"noun", gender:"ett", singular:"apotek", plural:"apotek" },
  { id:199, se:"musik", de:"Musik", cat:"noun", gender:"en", singular:"musik", plural:"musik" },
  { id:200, se:"film", de:"Film", cat:"noun", gender:"en", singular:"film", plural:"filmer" },
  { id:201, se:"sport", de:"Sport", cat:"noun", gender:"en", singular:"sport", plural:"sporter" },
  { id:202, se:"lek", de:"Spiel", cat:"noun", gender:"en", singular:"lek", plural:"lekar" },
  { id:203, se:"träd", de:"Baum", cat:"noun", gender:"ett", singular:"träd", plural:"träd" },
  { id:204, se:"blomma", de:"Blume", cat:"noun", gender:"en", singular:"blomma", plural:"blommor" },
  { id:205, se:"skog", de:"Wald", cat:"noun", gender:"en", singular:"skog", plural:"skogar" },
  { id:206, se:"sjö", de:"See", cat:"noun", gender:"en", singular:"sjö", plural:"sjöar" },
  { id:207, se:"hav", de:"Meer", cat:"noun", gender:"ett", singular:"hav", plural:"hav" },
  { id:208, se:"berg", de:"Berg", cat:"noun", gender:"ett", singular:"berg", plural:"berg" },
  { id:209, se:"ö", de:"Insel", cat:"noun", gender:"en", singular:"ö", plural:"öar" },
  { id:210, se:"färg", de:"Farbe", cat:"noun", gender:"en", singular:"färg", plural:"färger" },

  // === PRÄPOSITIONEN (ca. 25) ===
  { id:301, se:"i", de:"in / bei", cat:"prep" },
  { id:302, se:"på", de:"auf / an / in", cat:"prep" },
  { id:303, se:"för", de:"für / vor", cat:"prep" },
  { id:304, se:"med", de:"mit", cat:"prep" },
  { id:305, se:"av", de:"von / durch", cat:"prep" },
  { id:306, se:"till", de:"zu / nach / bis", cat:"prep" },
  { id:307, se:"om", de:"über / um / wenn", cat:"prep" },
  { id:308, se:"från", de:"von / aus", cat:"prep" },
  { id:309, se:"under", de:"unter / während", cat:"prep" },
  { id:310, se:"efter", de:"nach / hinter", cat:"prep" },
  { id:311, se:"vid", de:"bei / an", cat:"prep" },
  { id:312, se:"mot", de:"gegen / zu", cat:"prep" },
  { id:313, se:"över", de:"über", cat:"prep" },
  { id:314, se:"utan", de:"ohne", cat:"prep" },
  { id:315, se:"genom", de:"durch", cat:"prep" },
  { id:316, se:"mellan", de:"zwischen", cat:"prep" },
  { id:317, se:"bland", de:"unter / zwischen", cat:"prep" },
  { id:318, se:"inom", de:"innerhalb", cat:"prep" },
  { id:319, se:"hos", de:"bei (jemandem)", cat:"prep" },
  { id:320, se:"kring", de:"um / rund um", cat:"prep" },
  { id:321, se:"enligt", de:"laut / gemäß", cat:"prep" },
  { id:322, se:"trots", de:"trotz", cat:"prep" },
  { id:323, se:"sedan", de:"seit / dann", cat:"prep" },
  { id:324, se:"innan", de:"vor (zeitlich)", cat:"prep" },
  { id:325, se:"bakom", de:"hinter", cat:"prep" },

  // === RESTLICHE WÖRTER (Pronomen, Adverbien, Adjektive, Konjunktionen, etc.) ===
  { id:401, se:"och", de:"und", cat:"other" },
  { id:402, se:"att", de:"zu / dass", cat:"other" },
  { id:403, se:"det", de:"es / das", cat:"other" },
  { id:404, se:"en", de:"ein / eine (utrum)", cat:"other" },
  { id:405, se:"ett", de:"ein / eine (neutrum)", cat:"other" },
  { id:406, se:"den", de:"der / die / das (bestimmt)", cat:"other" },
  { id:407, se:"som", de:"der / die / das / wie", cat:"other" },
  { id:408, se:"jag", de:"ich", cat:"other" },
  { id:409, se:"vi", de:"wir", cat:"other" },
  { id:410, se:"inte", de:"nicht", cat:"other" },
  { id:411, se:"sig", de:"sich", cat:"other" },
  { id:412, se:"så", de:"so / also", cat:"other" },
  { id:413, se:"men", de:"aber", cat:"other" },
  { id:414, se:"man", de:"man", cat:"other" },
  { id:415, se:"du", de:"du", cat:"other" },
  { id:416, se:"han", de:"er", cat:"other" },
  { id:417, se:"de", de:"sie (Plural)", cat:"other" },
  { id:418, se:"mycket", de:"viel / sehr", cat:"other" },
  { id:419, se:"nu", de:"jetzt", cat:"other" },
  { id:420, se:"när", de:"wann / als", cat:"other" },
  { id:421, se:"all", de:"all / ganz", cat:"other" },
  { id:422, se:"någon", de:"jemand / irgendetwas", cat:"other" },
  { id:423, se:"denna", de:"dieser / diese", cat:"other" },
  { id:424, se:"annan", de:"anderer / andere", cat:"other" },
  { id:425, se:"eller", de:"oder", cat:"other" },
  { id:426, se:"bra", de:"gut", cat:"other" },
  { id:427, se:"stor", de:"groß", cat:"other" },
  { id:428, se:"hon", de:"sie (Singular)", cat:"other" },
  { id:429, se:"här", de:"hier", cat:"other" },
  { id:430, se:"där", de:"dort", cat:"other" },
  { id:431, se:"ny", de:"neu", cat:"other" },
  { id:432, se:"också", de:"auch", cat:"other" },
  { id:433, se:"även", de:"auch / sogar", cat:"other" },
  { id:434, se:"då", de:"dann / als", cat:"other" },
  { id:435, se:"ut", de:"hinaus / raus", cat:"other" },
  { id:436, se:"in", de:"hinein / rein", cat:"other" },
  { id:437, se:"hur", de:"wie", cat:"other" },
  { id:438, se:"lite", de:"ein wenig / wenig", cat:"other" },
  { id:439, se:"upp", de:"hoch / auf", cat:"other" },
  { id:440, se:"bara", de:"nur", cat:"other" },
  { id:441, se:"vad", de:"was", cat:"other" },
  { id:442, se:"två", de:"zwei", cat:"other" },
  { id:443, se:"än", de:"als / noch", cat:"other" },
  { id:444, se:"sen", de:"dann / später", cat:"other" },
  { id:445, se:"vilken", de:"welcher / welche", cat:"other" },
  { id:446, se:"ingen", de:"keiner / keine", cat:"other" },
  { id:447, se:"hel", de:"ganz / heil", cat:"other" },
  { id:448, se:"många", de:"viele", cat:"other" },
  { id:449, se:"ni", de:"ihr / Sie", cat:"other" },
  { id:450, se:"svensk", de:"schwedisch", cat:"other" },
  { id:451, se:"liten", de:"klein", cat:"other" },
  { id:452, se:"tidig", de:"früh", cat:"other" },
  { id:453, se:"ju", de:"ja / doch (Partikel)", cat:"other" },
  { id:454, se:"olik", de:"verschieden", cat:"other" },
  { id:455, se:"flera", de:"mehrere", cat:"other" },
  { id:456, se:"tre", de:"drei", cat:"other" },
  { id:457, se:"hög", de:"hoch", cat:"other" },
  { id:458, se:"själv", de:"selbst", cat:"other" },
  { id:459, se:"både", de:"beide", cat:"other" },
  { id:460, se:"helt", de:"ganz / völlig", cat:"other" },
  { id:461, se:"idag", de:"heute", cat:"other" },
  { id:462, se:"samt", de:"sowie / und", cat:"other" },
  { id:463, se:"kanske", de:"vielleicht", cat:"other" },
  { id:464, se:"egen", de:"eigen", cat:"other" },
  { id:465, se:"länge", de:"lange (Zeit)", cat:"other" },
  { id:466, se:"redan", de:"schon / bereits", cat:"other" },
  { id:467, se:"samma", de:"derselbe / dieselbe", cat:"other" },
  { id:468, se:"rätt", de:"richtig / Recht", cat:"other" },
  { id:469, se:"gammal", de:"alt", cat:"other" },
  { id:470, se:"viktig", de:"wichtig", cat:"other" },
  { id:471, se:"fler", de:"mehr (zählbar)", cat:"other" },
  { id:472, se:"ner", de:"runter / hinunter", cat:"other" },
  { id:473, se:"hem", de:"nach Hause / Zuhause", cat:"other" },
  { id:474, se:"nära", de:"nah / nahe", cat:"other" },
  { id:475, se:"varje", de:"jeder / jede", cat:"other" },
  { id:476, se:"just", de:"gerade / genau", cat:"other" },
  { id:477, se:"svår", de:"schwierig / schwer", cat:"other" },
  { id:478, se:"eftersom", de:"weil / da", cat:"other" },
  { id:479, se:"väl", de:"wohl / gut", cat:"other" },
  { id:480, se:"riktig", de:"richtig / echt", cat:"other" },
  { id:481, se:"fin", de:"schön / fein", cat:"other" },
  { id:482, se:"ja", de:"ja", cat:"other" },
  { id:483, se:"nej", de:"nein", cat:"other" },
  { id:484, se:"tack", de:"danke", cat:"other" },
  { id:485, se:"hej", de:"hallo / tschüss", cat:"other" },
  { id:486, se:"god", de:"gut", cat:"other" },
  { id:487, se:"snäll", de:"nett / freundlich", cat:"other" },
  { id:488, se:"rolig", de:"lustig / unterhaltsam", cat:"other" },
  { id:489, se:"tråkig", de:"langweilig", cat:"other" },
  { id:490, se:"vacker", de:"schön", cat:"other" },
  { id:491, se:"ful", de:"hässlich", cat:"other" },
  { id:492, se:"snabb", de:"schnell", cat:"other" },
  { id:493, se:"långsam", de:"langsam", cat:"other" },
  { id:494, se:"lång", de:"lang", cat:"other" },
  { id:495, se:"kort", de:"kurz", cat:"other" },
  { id:496, se:"varm", de:"warm / heiß", cat:"other" },
  { id:497, se:"kall", de:"kalt", cat:"other" },
  { id:498, se:"glad", de:"froh / glücklich", cat:"other" },
  { id:499, se:"ledsen", de:"traurig", cat:"other" },
  { id:500, se:"arg", de:"wütend / ärgerlich", cat:"other" },
];
